### ISSUE TITLE
Fade GIF

### ISSUE THREAD

**Issue by adam-paul952** [sherpa-code/CatCount#2]
```js
function checkForCat(hidingPlace) {
                if (catLocations.includes(hidingPlace.target.id)) {
                    alert("Found a cat!");
                    catsFound++;
                    document.getElementById("foundCounterValue").innerHTML = catsFound;
                     // TODO: below line should fade in the cat gif from display='none', let it play for a couple seconds, then fade out
                        // as-is, it simply hides the clickable area
                        // what is the best way to handle this for the child element (cat gif)?
                    document.getElementById(hidingPlace.target.id).style.display = 'none';

 /* --------- In the line above we set the display property to none, what do you think about setting the opacity to 0? ---------- */

                    // document.getElementById(hidingPlace.target.id).style.display = 'block';
                } else {
                    // TODO: Add visual feedback for finding a cat (display the cat gif; fade it in and out)
                }
                if (catsFound >= totalCats) {
                    // gameOver(true); // right now this is handled by the runTimer()
                }
            }
```

We have this animation:
```css
           @keyframes fadeIn {
                from {
                    opacity: 0;
                }
                to {
                    opacity: 1;
                }
            }

            @keyframes fadeOut {
                from {
                    opacity: 1;
                }
                to {
                    opacity: 0;
                }
            }
```

With that animation added to the `clickable--area catGif`
```js
  container.innerHTML = `<img class='catGif' id='cat${index}' src='/img/cat${index}.gif'>`; 
```
